name: Update News CMS

on:
  schedule:
    - cron: '0 0 * * *'      # 매일 자정에 실행
  workflow_dispatch:         # 수동 실행 가능

jobs:
  update-news:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Fetch Google Sheet & generate JSON
        run: node scripts/fetch-sheet.js

      - name: Commit and Push news.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions[bot]@users.noreply.github.com"
          git add output.json
          git commit -m "chore: update news.json from Google Sheets" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}